name: MS API do Catalogo NODE JS

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Iniciando os containeres"
        run: docker-compose -f docker-compose-prod.yaml up --build -d app elasticsearch

      - name: "Containers rodando"
        run: docker-compose ps

      # - name: "Aguardando elasticsearch"
      #   run: docker exec -t ms-catalog-app wait-for elasticsearch:9200 -t 120 --

      # - name: "Aguardando app"
      #   run: docker exec -t ms-catalog-app wait-for app:3001 -t 120 --

      # - name: "Chown in /var/www"
      #   run: docker exec -u root -t micro-videos-app chown -R www-data:www-data /var/www

      - name: "Executando testes frontend"
        run: docker exec -t micro-videos-app npm run test
