name: MS API do Catalogo NODE JS

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Iniciando os containeres"
        run: docker-compose -f docker-compose-prod.yaml up --build -d app elasticsearch

      - name: "Containers rodando"
        run: docker exec -u root -t ms-catalog-app wait-for elasticsearch:9200 -t 120 -- echo "elasticsearch running on port 9200"

      - name: "Aguardando app"
        run: docker exec -u root -t ms-catalog-app wait-for app:3001 -t 120 -- echo "app running on port 3001"

      - name: "Executando testes frontend"
        run: docker exec -u root -t ms-catalog-app npm run test
